### ISSUE TITLE
Links rendered as raw HTML

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2021#17]
https://2021.stateofthemap.org/sessions/7SUKCQ/ has raw HTML showing up `<a>...`

**Comment by jidanni** [comment]
https://2021.stateofthemap.org/sessions/QLVGQK/ also has hyperlinks, while not raw HTML, but still not rendered as hyperlinks.
So maybe the raw poster above was trying to make links work...

**Comment by tyrasd** [comment]
I fixed the links in the two mentioned talks now. (the website will update in <30 minutes)

Since these need to be fixed manually, I'd need to know which other talks are also affected. Did you spot more?

**Comment by tyrasd** [comment]
I found a few more places, which are fixed now. Please let us know if there are more non-functioning links.

**Comment by jidanni** [comment]
https://2021.stateofthemap.org/sessions/ZLK9X9/ at bottom.

**Comment by jidanni** [comment]
https://2021.stateofthemap.org/posters/ : many https in page.
