### ISSUE TITLE
Use four digits for times

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2021#18]
Please say 04:45.
```
Room: Track 1 - Talks

Sunday, 4:45 CST
Change time zone:
￼
Taiwan*
```
I can't tell you exactly why though.

**Comment by tyrasd** [comment]
This seems to be a case where there are different conventions in different countries/regions . I'd prefer to keep it as is, unless you can specify _why_ the leading 0 is actually preferable.

**Comment by jidanni** [comment]
Everybody knows that e.g., 4:05, at a conference, couldn't be in the wee hours of the morning, so must be 4:05 P.M.

But at this conference it could. Therefore there is no harm in writing 04:05.

Also [that's the format](https://www.gnu.org/software/pspp/manual/html_node/Time-and-Date-Formats.html) used by computers. Nobody ever dreamt otherwise. 

Any why don't you write 4:5 for 4:05 then?

**Comment by jidanni** [comment]
https://2021.stateofthemap.org/programme/ still affected. Or maybe it is cached. Timezone: try Taiwan.

**Comment by tyrasd** [comment]
it works for me:

![Screenshot_20210711-182053](https://user-images.githubusercontent.com/1927298/125202659-ca1e5000-e274-11eb-94be-8b722fed4392.png)
