### ISSUE TITLE
Mention if users can view conference later

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2021#21]
Users visiting https://2021.stateofthemap.org/ need to see a statement:
- Besides the live stream, archives of it will later be available at ...., or:
- No recording of the live stream will be made available later, for ... reasons.

That way they can decide if
- They must stay up all night long to watch it, or:
- They can watch it later at their lesiure.

Also say if the archive will be:
- Just the whole stream.
- Separated by sessions / talks.

**Comment by jidanni** [comment]
We observe e.g., ￼ https://2021.stateofthemap.org/sessions/9XQTVC/ many talks say
> This event will not be recorded

So mention if the only way to see these is to "stay up all night" to watch them live.
Or if even there will be no live...

**Comment by tyrasd** [comment]
added a short notice on the main page with 1df03f230c5f545c402e21cf025e6c09a558b8c3
