### ISSUE TITLE
Mention if conference papers will be available

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2021#22]
Looking at a typical page,
https://2021.stateofthemap.org/sessions/9XQTVC/
the user wonders if next week, there will be a link to a conference paper on this URL,
or if he needn't bother checking, as this conference doesn't have any traditional "conference papers".

**Comment by tyrasd** [comment]
@marcominghini could you tell us what we can write there as a placeholder?

**Comment by MarcoMinghini** [comment]
Dear @jidanni, thanks for the interest in the Academic Track!

We are currently preparing the Academic Track Proceedings, but they will most probably not be ready by the Academic Track sessions on Sunday. However, we will then have a link to each abstract published in the proceedings, so a good placeholder might be 'Abstract published in the conference proceedings'.
