### ISSUE TITLE
Add title of current talk/session to stream

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2021#23]
https://2021.stateofthemap.org/stream/ doesn't show the title of the current talk/session.

I just see three people talking.

Yes, one can check the schedule.

**Comment by jidanni** [comment]
![e](https://user-images.githubusercontent.com/1230959/125163012-ab10b700-e1bd-11eb-87da-5565158777fd.jpg)
(During discussion time.)

**Comment by tyrasd** [comment]
Good suggestion. Sadly there was not enough time during the conference to implement this for SotM 2021. I put this suggestion to our [feedback](https://wiki.openstreetmap.org/wiki/State_of_the_Map_2021/feedback) pad at https://pads.ccc.de/BTmogYuzQF.

**Comment by jidanni** [comment]
Glad you added it to Feedback.
