### ISSUE TITLE
stream lacks bandwidth control

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2021#24]
https://2021.stateofthemap.org/stream/ lacks a bandwidth / quality control (144p, ... 720p) knob.
Apparently the assumption is everybody has unlimited bandwidth.

**Comment by jidanni** [comment]
Also add 0p: no picture at all. For just listening, when no picture is needed.

**Comment by tyrasd** [comment]
Good suggestion(s). Sadly there was not enough time during the conference to implement this for SotM 2021. I put this suggestion to our [feedback](https://wiki.openstreetmap.org/wiki/State_of_the_Map_2021/feedback) pad at https://pads.ccc.de/BTmogYuzQF.
