### ISSUE TITLE
On program add big arrow pointing to current session (time block)

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2021#27]
On https://2021.stateofthemap.org/programme/
put a big red arrow, pointing to the current time block.

That way one wouldn't need to look at one's watch and look up and down the list.

In fact also add a floating / or sidebar link, always visible, that will scroll the window to the current time.

**Comment by jidanni** [comment]
Could use "javascript that affects CSS to cause the background of the current `<td>` to be pink" or something.

**Comment by tyrasd** [comment]
Good suggestion. Sadly there was not enough time during the conference to implement this for SotM 2021. I put this suggestion to our [feedback](https://wiki.openstreetmap.org/wiki/State_of_the_Map_2021/feedback) pad at https://pads.ccc.de/BTmogYuzQF.
