### ISSUE TITLE
Only half of the times have their day attached 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2021#30]
Yes there is a logic in having only half of the times have their day attached (Sun),
![20210710T214352](https://user-images.githubusercontent.com/1230959/125165090-08aa0100-e1c8-11eb-9e65-b69ed5ca4940.jpg)
But just as a present for us illogical people, please add the day to all of them, even Sat's.

**Comment by tyrasd** [comment]
it's only given for times where the (local timezone) day does not match the heading of the respective conference day.

**Comment by jidanni** [comment]
But at the scroll position shown above, there is no previous day!
The previous day is rolled up out of view!
